name: Jest Tests
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Run Jests Test
        run: yarn test
      - name: Generate coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn run test --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
          # threshold: 20 # TODO: Include this when we reach aceptable coverage %
