name: code linter

on: [push, pull_request]
  branches-ignore:
    - master
    - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run lint
        run: npm run lint
